// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtWtiwxdQvZOH4A3BiFb29kexotu6umoY',
    appId: '1:619444732168:web:e86b007724fc93b4552cbd',
    messagingSenderId: '619444732168',
    projectId: 'appforenvironment',
    authDomain: 'appforenvironment.firebaseapp.com',
    storageBucket: 'appforenvironment.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl-1xBy144T3RJbQ3brUxoeWArXdZOnz8',
    appId: '1:619444732168:android:c78779d71e8936d4552cbd',
    messagingSenderId: '619444732168',
    projectId: 'appforenvironment',
    storageBucket: 'appforenvironment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ79B7tJiwQ1OJpA9t4c_IO1cZeuQ1Y5w',
    appId: '1:619444732168:ios:5df3a285f82e689a552cbd',
    messagingSenderId: '619444732168',
    projectId: 'appforenvironment',
    storageBucket: 'appforenvironment.firebasestorage.app',
    iosBundleId: 'com.example.appforenvironment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ79B7tJiwQ1OJpA9t4c_IO1cZeuQ1Y5w',
    appId: '1:619444732168:ios:5df3a285f82e689a552cbd',
    messagingSenderId: '619444732168',
    projectId: 'appforenvironment',
    storageBucket: 'appforenvironment.firebasestorage.app',
    iosBundleId: 'com.example.appforenvironment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtWtiwxdQvZOH4A3BiFb29kexotu6umoY',
    appId: '1:619444732168:web:b3a441bc3ed4d7b5552cbd',
    messagingSenderId: '619444732168',
    projectId: 'appforenvironment',
    authDomain: 'appforenvironment.firebaseapp.com',
    storageBucket: 'appforenvironment.firebasestorage.app',
  );
}
